// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHIrJcNpjIRjOMq1P9RPqRJdmS-u-zHdQ',
    appId: '1:1083830612522:web:3f9e65a243f797bd198953',
    messagingSenderId: '1083830612522',
    projectId: 'userauth-330f6',
    authDomain: 'userauth-330f6.firebaseapp.com',
    databaseURL: 'https://userauth-330f6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'userauth-330f6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzcyPM_ZuYN2uzUQGIt2jIUcyT2uGcf0U',
    appId: '1:1083830612522:android:f1af935fb589e176198953',
    messagingSenderId: '1083830612522',
    projectId: 'userauth-330f6',
    databaseURL: 'https://userauth-330f6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'userauth-330f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeKJTBzKFooryrfqNW2kikmPfWEq-Tcuo',
    appId: '1:1083830612522:ios:31adde3984846bbd198953',
    messagingSenderId: '1083830612522',
    projectId: 'userauth-330f6',
    databaseURL: 'https://userauth-330f6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'userauth-330f6.appspot.com',
    iosClientId: '1083830612522-nn2frvbsmmm1hl8mssukrdl555vu7e2j.apps.googleusercontent.com',
    iosBundleId: 'com.example.testapp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeKJTBzKFooryrfqNW2kikmPfWEq-Tcuo',
    appId: '1:1083830612522:ios:31adde3984846bbd198953',
    messagingSenderId: '1083830612522',
    projectId: 'userauth-330f6',
    databaseURL: 'https://userauth-330f6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'userauth-330f6.appspot.com',
    iosClientId: '1083830612522-nn2frvbsmmm1hl8mssukrdl555vu7e2j.apps.googleusercontent.com',
    iosBundleId: 'com.example.testapp2',
  );
}
